project_id = "ghbnvodnnxgxkiufcael"

# Configure webhook for custom email
[auth.hook.send_email]
enabled = true
uri = "https://ghbnvodnnxgxkiufcael.supabase.co/functions/v1/send-custom-auth-email"
secrets = []

[functions.generate-recommendations]
verify_jwt = false

[functions.filter-recommendations]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false