project_id = "ghbnvodnnxgxkiufcael"

# Configure webhook for custom email
[auth.hook.send_email]
enabled = true
uri = "https://ghbnvodnnxgxkiufcael.supabase.co/functions/v1/send-custom-auth-email"
secrets = ["SEND_EMAIL_HOOK_SECRET"]

[functions.generate-recommendations]
verify_jwt = false

[functions.filter-recommendations]
verify_jwt = false

[functions.send-custom-auth-email]
verify_jwt = false

[functions.send-property-manager-notification]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.batch-recommendations]
verify_jwt = false

[functions.fetch-events]
verify_jwt = false

[functions.check-cache]
verify_jwt = false

[functions.get-eligible-survey-question]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = true

[functions.check-subscription-status]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true